import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/assets/styles/main.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import Header from "@/components/templates/header/Header";
import Footer from "@/components/templates/footer/Footer";

const geistSans = localFont({
  src: "../assets/styles/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/styles/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Header />
          <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]" style={{ minHeight: "calc(100vh - 72px)" }}>
            <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
              {children}
            </main>
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
